# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# Default values for arvados.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: Always

# The external IP address for this Arvados cluster.
# Must be set to a valid IP address, e.g. by using --set when invoking helm
externalIP: ~

# The default e-mail address and password for the initial cluster admin user
adminUserEmail: "test@example.com"
adminUserPassword: "passw0rd"

# A super user token
superUserSecret: "thisisnotaverygoodsuperusersecretstring00000000000"
# An anonymous user token
anonymousUserSecret: "thisisnotaverygoodanonymoussecretstring00000000000"

# The number of compute nodes to spin up
compute:
  nodes: 4

# The cluster identifier, a 5 character alphanumeric string
uuidPrefix: vwxyz

# The package versions for this Arvados cluster. Also see
#
#   curl http://versions.arvados.org/v1/commit/ | jq .
#
arvados:
  versions:
    distribution:
      arvadosApiServer: 1.3.0-1
      arvadosGitHttpd: 1.3.0-1
      arvadosHealth: 1.3.0-1
      arvadosWorkbench: 1.3.0-1
      arvadosWs: 1.3.0-1
      arvadosSSOServer: 1.1.4-1
      crunchDispatchSlurm: 1.3.0-1
      crunchRun: 1.3.0-1
      crunchRunner: 1.3.0-1
      keepBalance: 1.3.0-1
      keepStore: 1.3.0-1
      keepWeb: 1.3.0-1
      keepProxy: 1.3.0-1
      libPamArvados: 1.3.0-1
      pythonArvadosFuse: 1.3.0-1
      pythonArvadosPythonClient: 1.3.0-1
    gem:
      arvados: 1.3.0.20181129194931
      arvadosCLI: 1.3.0.20181129194931
      arvadosLoginSync: 1.3.0.20181129194931
