# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# Default values for arvados.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: Always

# The external IP address for this Arvados cluster.
# Must be set to a valid IP address, e.g. by using --set when invoking helm
externalIP: ~

# A list of CIDRs that have direct access to the Keep store service. All other
# IP addresses will use the Keep proxy.
# If hosts outside your cluster are in the default range (10.0.0.0/8), change
# this to the exact CIDR of your cluster.
# If using MetaLB with apiServerExternalTrafficPolicy set to Cluster, set this
# to an empty list, since the source IP will be obscured.
internalIPs: [10.0.0.0/8]

loadBalancer:
  # Annotations to add to all LoadBalancer Services.
  # This is required for MetalLB, since the same externalIP is reused for all
  # services, and sharing is disabled by default.
  # metallb.universe.tf/allow-shared-ip: arbitrary-sharing-key
  annotations:

  # externalTrafficPolicy for the api-server-service
  # Set to Cluster if using MetalLB, otherwise an externalIP won't be allocated
  apiServerExternalTrafficPolicy: Local

# The default e-mail address and password for the initial cluster admin user
adminUserEmail: "test@example.com"
adminUserPassword: "passw0rd"

# A super user token
superUserSecret: "thisisnotaverygoodsuperusersecretstring00000000000"
# An anonymous user token
anonymousUserSecret: "thisisnotaverygoodanonymoussecretstring00000000000"

# The number of compute nodes to spin up
compute:
  nodes: 4

# The cluster identifier, a 5 character alphanumeric string
uuidPrefix: vwxyz

# The package versions for this Arvados cluster. Also see
#
#   curl http://versions.arvados.org/v1/commit/ | jq .
#
arvados:
  versions:
    distribution:
      arvadosApiServer: 2.1.1-1
      arvadosController: 2.1.1-1
      arvadosGitHttpd: 2.1.1-1
      arvadosHealth: 2.1.1-1
      arvadosWorkbench: 2.1.1-1
      arvadosWorkbench2: 2.1.1-1
      arvadosWs: 2.1.1-1
      crunchDispatchSlurm: 2.1.1-1
      crunchRun: 2.1.1-1
      crunchRunner: 2.1.1-1
      keepBalance: 2.1.1-1
      keepStore: 2.1.1-1
      keepWeb: 2.1.1-1
      keepProxy: 2.1.1-1
      libPamArvados: 2.1.1-1
      pythonArvadosFuse: 2.1.1-1
      pythonArvadosPythonClient: 2.1.1-1
    gem:
      arvados: 2.1.1
      arvadosCLI: 2.1.1
      arvadosLoginSync: 2.1.1

postgres:
  persistence:
    enabled: true
    storageClass: ~
    size: 8Gi

keep:
  persistence:
    enabled: true
    storageClass: ~
    size: 64Gi

# A custom bundle of CA certificates to use.
# Useful for corporate networks with TLS proxies.
# Set it by using the --set-file Helm argument.
customCABundle: ""
