# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# Default values for arvados.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: Always

# The external IP address for this Arvados cluster.
# Must be set to a valid IP address, e.g. by using --set when invoking helm
externalIP: ~

# The default e-mail address and password for the initial cluster admin user
adminUserEmail: "test@example.com"
adminUserPassword: "passw0rd"

# A super user token
superUserSecret: "thisisnotaverygoodsuperusersecretstring00000000000"
# An anonymous user token
anonymousUserSecret: "thisisnotaverygoodanonymoussecretstring00000000000"

# The number of compute nodes to spin up
compute:
  nodes: 4

# The cluster identifier, a 5 character alphanumeric string
uuidPrefix: vwxyz

# The package versions for this Arvados cluster. Also see
#
#   curl http://versions.arvados.org/v1/commit/ | jq .
#
arvados:
  versions:
    distribution:
      arvadosApiServer: 2.0.2-1
      arvadosController: 2.0.2-1
      arvadosGitHttpd: 2.0.2-1
      arvadosHealth: 2.0.2-1
      arvadosWorkbench: 2.0.2-1
      arvadosWorkbench2: 2.0.2-1
      arvadosWs: 2.0.2-1
      arvadosSSOServer: 1.1.4-1
      crunchDispatchSlurm: 2.0.2-1
      crunchRun: 2.0.2-1
      crunchRunner: 2.0.2-1
      keepBalance: 2.0.2-1
      keepStore: 2.0.2-1
      keepWeb: 2.0.2-1
      keepProxy: 2.1.0.dev20200422013447-1
      libPamArvados: 2.0.2-1
      pythonArvadosFuse: 2.0.2-1
      pythonArvadosPythonClient: 2.0.2-1
    gem:
      arvados: 2.0.2
      arvadosCLI: 2.0.2
      arvadosLoginSync: 2.0.2

# A custom bundle of CA certificates to use.
# Useful for corporate networks with TLS proxies.
# Set it by using the --set-file Helm argument.
customCABundle: ""
