# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: arvados-api-server
  labels:
    app: {{ template "arvados.name" . }}
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.loadBalancer.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: {{ .Values.loadBalancer.apiServerExternalTrafficPolicy }}
  loadBalancerIP: {{ required "A valid externalIP is required!" .Values.externalIP }}
  ports:
  - name: http
    port: 444
    targetPort: 444
    protocol: TCP
  selector:
    app: arvados-api-server
