# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "arvados-keep-web"
  labels:
    app: arvados-keep-web
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: arvados-keep-web
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: arvados-keep-web
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: arvados-keep-web
          image: "cure/arvados-runtime"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "/usr/local/bin/bootstrap.sh mime-support keep-web={{ .Values.arvados.versions.distribution.keepWeb }} && keep-web"
          env:
            - name : ARVADOS_API_HOST
              value: "{{ .Values.externalIP }}:444"
            - name : ARVADOS_API_HOST_INSECURE
              value: "true"
            - name : ARVADOS_API_TOKEN
              value: "{{ .Values.anonymousUserSecret }}"
          volumeMounts:
            - name: etc-configmap
              mountPath: /etc/arvados/config.yml
              subPath: config.yml
        - name: arvados-keep-web-https
          image: "nginx:1.17"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nginx-configmap
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: ssl-configmap
              mountPath: /etc/nginx/ssl.crt
              subPath: cert
            - name: ssl-configmap
              mountPath: /etc/nginx/ssl.key
              subPath: key
      volumes:
        - name: etc-configmap
          configMap:
            name: etc-configmap
        - name: ssl-configmap
          configMap:
            name: ssl-configmap
        - name: nginx-configmap
          configMap:
            name: arvados-keep-web-https-configmap
