# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: arvados-keep-web
  labels:
    app: {{ template "arvados.name" . }}
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.loadBalancer.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ required "A valid externalIP is required!" .Values.externalIP }}
  ports:
  - name: https
    port: 9002
    targetPort: 9002
    protocol: TCP
  selector:
    app: arvados-keep-web
