# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "arvados-keep-store"
  labels:
    app: arvados-keep-store
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 2
  podManagementPolicy: Parallel
  serviceName: arvados-keep-store
  selector:
    matchLabels:
      app: arvados-keep-store
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: arvados-keep-store
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: arvados-keep-store
          image: "cure/arvados-runtime"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "mkdir /keepdata && /usr/local/bin/bootstrap.sh keepstore={{ .Values.arvados.versions.distribution.keepStore }} && GOGC=10 keepstore"
          volumeMounts:
            - name: etc-configmap
              mountPath: /etc/arvados/config.yml
              subPath: config.yml
      volumes:
        - name: etc-configmap
          configMap:
            name: etc-configmap

