# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "arvados-workbench"
  labels:
    app: arvados-workbench
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: arvados-workbench
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: arvados-workbench
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: arvados-workbench
          image: "cure/arvados-rails-runtime"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "/usr/local/bin/bootstrap.sh arvados-workbench={{ .Values.arvados.versions.distribution.arvadosWorkbench }} arvados-workbench2={{ .Values.arvados.versions.distribution.arvadosWorkbench2 }} && exec /sbin/my_init"
          env:
            - name: RAILS_ENV
              value: "production"
          volumeMounts:
            - name: etc-configmap
              mountPath: /etc/arvados/config.yml
              subPath: config.yml
            - name: workbench-configmap
              mountPath: /etc/arvados/workbench/application.yml
              subPath: application.yml
            - name: workbench-configmap
              mountPath: /etc/nginx/sites-enabled/workbench.conf
              subPath: nginx.conf
            - name: ssl-configmap
              mountPath: /etc/ssl/certs/workbench.pem
              subPath: cert
            - name: ssl-configmap
              mountPath: /etc/ssl/private/workbench.key
              subPath: key
            {{- if .Values.customCABundle }}
            - name: custom-ca-bundle-volume
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: custom-ca-bundle.pem
            {{- end }}
      volumes:
        - name: etc-configmap
          configMap:
            name: etc-configmap
        - name: workbench-configmap
          configMap:
            name: arvados-workbench-configmap
        - name: ssl-configmap
          configMap:
            name: ssl-configmap
        {{- if .Values.customCABundle }}
        - name: custom-ca-bundle-volume
          configMap:
            name: custom-ca-bundle-configmap
        {{- end }}

