# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: arvados-workbench
  labels:
    app: {{ template "arvados.name" . }}
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ required "A valid externalIP is required!" .Values.externalIP }}
  ports:
  - name: wb2
    port: 443
    targetPort: 443
    protocol: TCP
  - name: wb
    port: 445
    targetPort: 445
    protocol: TCP
  selector:
    app: arvados-workbench
