# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "arvados-ws"
  labels:
    app: arvados-ws
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: arvados-ws
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: arvados-ws
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: arvados-ws
          image: "cure/arvados-rails-runtime"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "/usr/local/bin/bootstrap.sh arvados-ws={{ .Values.arvados.versions.distribution.arvadosWs }} && arvados-ws"
          volumeMounts:
            - name: etc-configmap
              mountPath: /etc/arvados/config.yml
              subPath: config.yml
        - name: arvados-ws-https
          image: "nginx:1.17"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nginx-configmap
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: ssl-configmap
              mountPath: /etc/nginx/ssl.crt
              subPath: cert
            - name: ssl-configmap
              mountPath: /etc/nginx/ssl.key
              subPath: key
      volumes:
        - name: etc-configmap
          configMap:
            name: etc-configmap
        - name: ssl-configmap
          configMap:
            name: ssl-configmap
        - name: nginx-configmap
          configMap:
            name: arvados-ws-https-configmap
